<?php

use Illuminate\Database\Seeder;

class AreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Area::create(['nombre' => 'Abastecimiento', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'AGA - Asociación Gremial de Académicos', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Análisis Institucional', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Asistencia Religiosa', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Aula Virtual', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Biblioteca Casa Central'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Bienestar y Capacitación', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Capitulo Académico', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Casino Casa Central'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'CEA - Centro de Estudios Avanzados y Extensión', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'CEAL - Centro de Estudios y Asistencia Legislativa', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Centro Costa Digital PUCV' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Centro Vincular PUCV', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'CERES – Centro Regional de Innovación Hortofrutícola de Valparaíso', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Ciencias Religiosas'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Cineteca', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Club de Campo' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'CONEDUCA', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Contraloría'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Control de Inventario' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Crédito y Cobranza', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Cultura Religiosa' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'DAC - Dirección Aseguramiento de la Calidad'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'DAE - Dirección de Asuntos Estudiantiles', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'DDCYF - Dirección de Desarrollo Curricular y Formativo', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'DEA - Dirección de Estudios Avanzados' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'DIDER - Dirección de Deportes y Recreación', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Dirección de Biblioteca'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Dirección de Comunicaciones'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Dirección de Innovación y Emprendimiento', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Dirección de Operación y Servicios', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'DPD - Dirección de Procesos Docentes', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'DPM - Dirección de Plan Maestro'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'DRI - Dirección de Relaciones Internacionales' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'DSIC - Dirección de Servicios de Informática y Comunicaciones' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Escuela de Derecho', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'EXPLORA'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'FE-PUCV – Federación de Estudiantes'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Finanzas', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'FSCU - Fondo Solidario de Crédito Universitario'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Incubadora', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Instituto de Ciencias Religiosas', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Mantención', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Movilización', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'OCT - Oficina de Cooperación Técnica', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Oficina Técnica de Vicerrectoría', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Perfeccionamiento Académico'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Prevención de Riesgos' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'PRODEPAM - Programa de Educación para Adultos Mayores' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Programa Beta' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Programa Calidad de Servicio', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Programa CRECES'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Programa de Inglés', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Prosecretaria' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Recepción Casa Central', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'RRHH - Dirección de Recursos Humanos', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Secretaria General', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Servicio de Alimentación', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Tesorería' , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'UGE - Unidad de Gestión Estudiantil'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Unidad de Gestión y Control de Obras', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Unidad de Servicios'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Instituto de Estadística', 'sede_id' =>  2]);
        App\Area::create(['nombre' => 'Escuela de Negocios y Economía', 'sede_id' =>  3]);
        App\Area::create(['nombre' => 'Escuela de Comercio'   , 'sede_id' =>  3]);
        App\Area::create(['nombre' => 'Escuela de Trabajo Social' , 'sede_id' =>  3]);
        App\Area::create(['nombre' => 'Biblioteca Gimpert', 'sede_id' =>  3]);
        App\Area::create(['nombre' => 'Casino Gimpert', 'sede_id' =>  3]);
        App\Area::create(['nombre' => 'Recepción Gimpert' , 'sede_id' =>  3]);
        App\Area::create(['nombre' => 'Escuela de Ingeniería Civil'   , 'sede_id' =>  4]);
        App\Area::create(['nombre' => 'Escuela de Ingeniería en Construcción' , 'sede_id' =>  4]);
        App\Area::create(['nombre' => 'Escuela de Ingeniería Eléctrica'   , 'sede_id' =>  4]);
        App\Area::create(['nombre' => 'Escuela de Ingeniería Química' , 'sede_id' =>  4]);
        App\Area::create(['nombre' => 'Escuela de Ingeniería de Transporte'   , 'sede_id' =>  4]);
        App\Area::create(['nombre' => 'LEPUCV - Laboratorio de Ensayos'   , 'sede_id' =>  4]);
        App\Area::create(['nombre' => 'Proyecto Ingeniería 2030', 'sede_id' =>  4]);
        App\Area::create(['nombre' => 'Biblioteca FIN', 'sede_id' =>  4]);
        App\Area::create(['nombre' => 'Casino FIN', 'sede_id' =>  4]);
        App\Area::create(['nombre' => 'Recepción FIN' , 'sede_id' =>  4]);
        App\Area::create(['nombre' => 'Decanato FIN', 'sede_id' =>  4]);
        App\Area::create(['nombre' => 'Escuela de Ingeniería Industrial', 'sede_id' =>  5]);
        App\Area::create(['nombre' => 'Escuela de Ingeniería Informática' , 'sede_id' =>  5]);
        App\Area::create(['nombre' => 'Instituto de Geografía', 'sede_id' =>  5]);
        App\Area::create(['nombre' => 'Recepción IBC' , 'sede_id' =>  5]);
        App\Area::create(['nombre' => 'Instituto de Matemáticas', 'sede_id' =>  6]);
        App\Area::create(['nombre' => 'Biblioteca Matemáticas', 'sede_id' =>  6]);
        App\Area::create(['nombre' => 'Casino IMA', 'sede_id' =>  6]);
        App\Area::create(['nombre' => 'Instituto de Música'   , 'sede_id' =>  7]);
        App\Area::create(['nombre' => 'Conservatorio Música', 'sede_id' =>  7]);
        App\Area::create(['nombre' => 'Escuela de Arquitectura y Diseño', 'sede_id' =>  8]);
        App\Area::create(['nombre' => 'Escuela de Ciencias del Mar'   , 'sede_id' =>  9]);
        App\Area::create(['nombre' => 'Recepción Ciencias del Mar', 'sede_id' =>  9]);
        App\Area::create(['nombre' => 'Casino Ciencias del Mar'   , 'sede_id' =>  9]);
        App\Area::create(['nombre' => 'Escuela de Alimentos', 'sede_id' =>  10  ]);
        App\Area::create(['nombre' => 'Biblioteca Alimentos', 'sede_id' =>  10  ]);
        App\Area::create(['nombre' => 'Instituto de Historia' , 'sede_id' =>  11  ]);
        App\Area::create(['nombre' => 'Casino de Historia', 'sede_id' =>  11  ]);
        App\Area::create(['nombre' => 'Escuela de Agronomía', 'sede_id' =>  12  ]);
        App\Area::create(['nombre' => 'Planta Experimental'   , 'sede_id' =>  12  ]);
        App\Area::create(['nombre' => 'Biblioteca Agronomía', 'sede_id' =>  12  ]);
        App\Area::create(['nombre' => 'Instituto de Arte' , 'sede_id' =>  13  ]);
        App\Area::create(['nombre' => 'Escuela de Ingeniería Mecánica', 'sede_id' =>  14  ]);
        App\Area::create(['nombre' => 'Biblioteca Mecánica'   , 'sede_id' =>  14  ]);
        App\Area::create(['nombre' => 'Recepción Ingeniería Mecánica' , 'sede_id' =>  14  ]);
        App\Area::create(['nombre' => 'Escuela de Ingeniería Bioquímica', 'sede_id' =>  15  ]);
        App\Area::create(['nombre' => 'Escuela de Psicología' , 'sede_id' =>  16  ]);
        App\Area::create(['nombre' => 'Escuela de Pedagogía', 'sede_id' =>  16  ]);
        App\Area::create(['nombre' => 'Escuela de Educación Física'   , 'sede_id' =>  16  ]);
        App\Area::create(['nombre' => 'Instituto de Filosofía', 'sede_id' =>  16  ]);
        App\Area::create(['nombre' => 'Instituto de Literatura y Ciencias del Lenguaje'   , 'sede_id' =>  16  ]);
        App\Area::create(['nombre' => 'Colegio Rubén Castro', 'sede_id' =>  16  ]);
        App\Area::create(['nombre' => 'Casino Sausalito', 'sede_id' =>  16  ]);
        App\Area::create(['nombre' => 'Recepción Sausalito'   , 'sede_id' =>  16  ]);
        App\Area::create(['nombre' => 'Decanato Filosofía y Educación', 'sede_id' =>  16  ]);
        App\Area::create(['nombre' => 'Instituto de Biología' , 'sede_id' =>  17  ]);
        App\Area::create(['nombre' => 'Instituto de Química', 'sede_id' =>  17  ]);
        App\Area::create(['nombre' => 'Instituto de Física'   , 'sede_id' =>  17  ]);
        App\Area::create(['nombre' => 'Escuela de Periodismo' , 'sede_id' =>  17  ]);
        App\Area::create(['nombre' => 'Programa de Bachillerato en Ciencias', 'sede_id' =>  17  ]);
        App\Area::create(['nombre' => 'Escuela de Kinesiología'   , 'sede_id' =>  17  ]);
        App\Area::create(['nombre' => 'Carrera de Tecnología Médica', 'sede_id' =>  17  ]);
        App\Area::create(['nombre' => 'NBC - Núcleo Biotecnología Curauma', 'sede_id' =>  17  ]);
        App\Area::create(['nombre' => 'CREAS - Centro Regional de Estudios en Alimentos y Salud', 'sede_id' =>  17  ]);
        App\Area::create(['nombre' => 'Casino Curauma', 'sede_id' =>  17  ]);
        App\Area::create(['nombre' => 'Decanato de Ciencias', 'sede_id' =>  17  ]);
        App\Area::create(['nombre' => 'Centro de Estudio Avanzados y Extensión'   , 'sede_id' =>  19  ]);
        App\Area::create(['nombre' => 'Sede la Calera', 'sede_id' =>  20  ]);
        App\Area::create(['nombre' => 'Sede la Ligua' , 'sede_id' =>  20  ]);
        App\Area::create(['nombre' => 'Sede Limache', 'sede_id' =>  20  ]);
        App\Area::create(['nombre' => 'Sede Quillota' , 'sede_id' =>  20  ]);
        App\Area::create(['nombre' => 'Sede Valparaíso'   , 'sede_id' =>  20  ]);
        App\Area::create(['nombre' => 'Sede Viña del Mar' , 'sede_id' =>  20  ]);
        App\Area::create(['nombre' => 'Ediciones Universitarias', 'sede_id' =>  21  ]);
        App\Area::create(['nombre' => 'Programa de Movilidad Estudiantil - DRI'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Unidad de mantención', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Laboratorio de suelos' , 'sede_id' =>  22  ]);
        App\Area::create(['nombre' => 'Laboratorio de suelos' , 'sede_id' =>  12  ]);
        App\Area::create(['nombre' => 'Oficina Beneficio a las Personas', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Dirección de Administración'   , 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'DPPA Cooperación Internacional', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Unidad de Servicios y Vigilancia', 'sede_id' =>  1]);
        App\Area::create(['nombre' => 'Procesos Tecnicos' , 'sede_id' =>  1]);   
    }
}
